name = "blog-count"
apiToken: ${{ secrets.CF_API_TOKEN }}
account_id = ${{ secrets.CF_ACCOUNT_ID }}
compatibility_date = "2025-03-25" 
main = "src/index.js"
workers_dev = false    

[[d1_databases]]
binding = "DB"
database_name = "FluxMonitor"  
database_id = "d86fca60-255b-49cc-b467-ea2d5c94b998" 

[observability.logs]
enabled = true